### PR TITLE
Correct the interrupt order, add some documentation and fix the inter…

### LINKED ISSUE #67: Interrupt handling not properly implemented
Currently interrupt handling doesn't seem to be implemented at all. At least not properly.

In the Arduino core libraries, we reach at this line:

https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/WInterrupts.c#L293

This effectively causes the interrupts to be mixed up. "INT1" actually is reported as interrupt "3".

I guess the easiest way to fix this would be if you modify your **digitalPinToInterrupt** to also be "mixed up" the way the Arduino core libraries expect it.

If I completely ignore "digitalPinToInterrupt" and just "attachInterrupt" to "3", then I have proper interrupts from INT1.

### PR DESCRIPTION
**Pull request by M-Reimer**
…rupt numbers in pin description

Fixes #67

### CODE REVIEW

**Comment by NicoHood** [comment]
Could you please remove the ordering fix, assuming arduino will merge your other patch? Because the documentation patch looks correct to me, thanks for having a closer look!

**Comment by M-Reimer** [comment]
No problem, but I'll wait for my other pull-request to be accepted, first.

**Comment by M-Reimer** [comment]
Do you still have hope that this will ever be merged in the AVR core repo?

**Comment by NicoHood** [comment]
Lets give it another try.
(Link to PR: https://github.com/arduino/ArduinoCore-avr/pull/66)

**Comment by NicoHood** [comment]
This can be also closed now, correct?

**Comment by M-Reimer** [comment]
If you've already added my documentation fix (didn't check so far) then yes, feel free to close

**Comment by NicoHood** [comment]
Thanks for the hint!

**Pull request closed without merging**
