### PR TITLE
Make HoodLoader2 examples appear in File>Examples

### PR DESCRIPTION
**Pull request by per1234**
As requested in https://github.com/arduino/Arduino/issues/3857
Examples only appear when a HoodLoader2 board is selected in the Board menu.
Tested with manual and Boards Manager install with hourly build and 1.6.5r5
clipboard01

### CODE REVIEW

**Comment by NicoHood** [comment]
Woah! Great idea!

Does it also work if you switch the boards? I think i've tried something similar but it only worked when the ide started with the correct selected board.  Not sure if this is still there. mazbe this can help us:
https://github.com/arduino/Arduino/pull/3847#issuecomment-143492239

**Comment by per1234** [comment]
>Does it also work if you switch the boards?
Yes, I just checked and with 1.6.6 and 1.6.5r5 I can select a non-HoodLoader2 board and then close the IDE and then reopen the IDE and then select a HoodLoader2 board and the HoodLoader examples appear.

**Comment by NicoHood** [comment]
Does it work without closing? That is important. Otherwise the user will wonder where the examples are. closing is not trivial and a bug (of the ide).

**Comment by per1234** [comment]
I'm not sure what you mean. I can select a non-Hoodloader2 board and the examples don't appear, then select a hoodloader2 board and the examples occur and the select a non-hoodloader2 board and the examples don't appear, etc. This works whether the IDE was opened with a hoodloader2 or a non-hoodloader2 board selected

**Comment by NicoHood** [comment]
Gave it a quick test, seems to work. Brilliant!! Thanks a lot again :)

**Pull request merged**
